In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [2]:
loan = pd.read_csv("loan_data 2.csv")
loan

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [3]:
loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

In [4]:
loan.columns

Index(['person_age', 'person_gender', 'person_education', 'person_income',
       'person_emp_exp', 'person_home_ownership', 'loan_amnt', 'loan_intent',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', 'previous_loan_defaults_on_file', 'loan_status'],
      dtype='object')

In [5]:
loan.isnull().sum()

person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [6]:
loan.isna().sum()

person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [7]:
loan["person_age"].unique()

array([ 22.,  21.,  25.,  23.,  24.,  26., 144., 123.,  20.,  32.,  34.,
        29.,  33.,  28.,  35.,  31.,  27.,  30.,  36.,  40.,  50.,  45.,
        37.,  39.,  44.,  43.,  41.,  46.,  38.,  47.,  42.,  48.,  49.,
        58.,  65.,  51.,  53.,  66.,  61.,  54.,  57.,  59.,  62.,  60.,
        55.,  52.,  64.,  70.,  78.,  69.,  56.,  73.,  63.,  94.,  80.,
        84.,  76.,  67., 116., 109.])

In [8]:
loan["person_gender"].unique()

array(['female', 'male'], dtype=object)

In [9]:
loan["person_gender"].value_counts()

person_gender
male      24841
female    20159
Name: count, dtype: int64

In [10]:
loan["person_gender"] = [1 if i == "male" else 0 for i in loan["person_gender"]]
loan

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,0,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,0,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,0,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,0,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,1,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,0,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,1,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,1,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,1,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [11]:
loan["person_education"].value_counts()

person_education
Bachelor       13399
Associate      12028
High School    11972
Master          6980
Doctorate        621
Name: count, dtype: int64

In [12]:
# loan["person_education"] = [0 if i == "High School" else 1 if i == "Bachelor" else 2 if i == "Master" else 3 if i == "Associate" else 4 if i == "Doctorate" else 5 for i in loan["person_education"]]
# loan

In [13]:
loan = pd.get_dummies(loan, columns=["person_education"], dtype=np.int8)
loan

,person_age,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status,person_education_Associate,person_education_Bachelor,person_education_Doctorate,person_education_High School,person_education_Master
0,22.0,0,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1,0,0,0,0,1
1,21.0,0,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0,0,0,0,1,0
2,25.0,0,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1,0,0,0,1,0
3,23.0,0,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1,0,1,0,0,0
4,24.0,1,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1,1,0,0,0,0
44996,37.0,0,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1,1,0,0,0,0
44997,33.0,1,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1,1,0,0,0,0
44998,29.0,1,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1,0,1,0,0,0
44999,24.0,1,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1,0,0,0,1,0

In [14]:
loan = pd.get_dummies(loan, columns=["person_home_ownership"], dtype=np.int8)
loan

,person_age,person_gender,person_income,person_emp_exp,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,...,loan_status,person_education_Associate,person_education_Bachelor,person_education_Doctorate,person_education_High School,person_education_Master,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT
0,22.0,0,71948.0,0,35000.0,PERSONAL,16.02,0.49,3.0,561,...,1,0,0,0,0,1,0,0,0,1
1,21.0,0,12282.0,0,1000.0,EDUCATION,11.14,0.08,2.0,504,...,0,0,0,0,1,0,0,0,1,0
2,25.0,0,12438.0,3,5500.0,MEDICAL,12.87,0.44,3.0,635,...,1,0,0,0,1,0,1,0,0,0
3,23.0,0,79753.0,0,35000.0,MEDICAL,15.23,0.44,2.0,675,...,1,0,1,0,0,0,0,0,0,1
4,24.0,1,66135.0,1,35000.0,MEDICAL,14.27,0.53,4.0,586,...,1,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,47971.0,6,15000.0,MEDICAL,15.66,0.31,3.0,645,...,1,1,0,0,0,0,0,0,0,1
44996,37.0,0,65800.0,17,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,...,1,1,0,0,0,0,0,0,0,1
44997,33.0,1,56942.0,7,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,...,1,1,0,0,0,0,0,0,0,1
44998,29.0,1,33164.0,4,12000.0,EDUCATION,13.23,0.36,6.0,604,...,1,0,1,0,0,0,0,0,0,1
44999,24.0,1,51609.0,1,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,...,1,0,0,0,1,0,0,0,0,1

In [15]:
loan = pd.get_dummies(loan, columns=["loan_intent"], dtype=np.int8)
loan

,person_age,person_gender,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,...,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,22.0,0,71948.0,0,35000.0,16.02,0.49,3.0,561,No,...,0,0,0,1,0,0,0,0,1,0
1,21.0,0,12282.0,0,1000.0,11.14,0.08,2.0,504,Yes,...,0,0,1,0,0,1,0,0,0,0
2,25.0,0,12438.0,3,5500.0,12.87,0.44,3.0,635,No,...,1,0,0,0,0,0,0,1,0,0
3,23.0,0,79753.0,0,35000.0,15.23,0.44,2.0,675,No,...,0,0,0,1,0,0,0,1,0,0
4,24.0,1,66135.0,1,35000.0,14.27,0.53,4.0,586,No,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,47971.0,6,15000.0,15.66,0.31,3.0,645,No,...,0,0,0,1,0,0,0,1,0,0
44996,37.0,0,65800.0,17,9000.0,14.07,0.14,11.0,621,No,...,0,0,0,1,0,0,1,0,0,0
44997,33.0,1,56942.0,7,2771.0,10.02,0.05,10.0,668,No,...,0,0,0,1,1,0,0,0,0,0
44998,29.0,1,33164.0,4,12000.0,13.23,0.36,6.0,604,No,...,0,0,0,1,0,1,0,0,0,0
44999,24.0,1,51609.0,1,6665.0,17.05,0.13,3.0,628,No,...,0,0,0,1,1,0,0,0,0,0

In [16]:
loan["previous_loan_defaults_on_file"] = [1 if i == "Yes" else 0 for i in loan["previous_loan_defaults_on_file"]]
loan

,person_age,person_gender,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,...,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,22.0,0,71948.0,0,35000.0,16.02,0.49,3.0,561,0,...,0,0,0,1,0,0,0,0,1,0
1,21.0,0,12282.0,0,1000.0,11.14,0.08,2.0,504,1,...,0,0,1,0,0,1,0,0,0,0
2,25.0,0,12438.0,3,5500.0,12.87,0.44,3.0,635,0,...,1,0,0,0,0,0,0,1,0,0
3,23.0,0,79753.0,0,35000.0,15.23,0.44,2.0,675,0,...,0,0,0,1,0,0,0,1,0,0
4,24.0,1,66135.0,1,35000.0,14.27,0.53,4.0,586,0,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,47971.0,6,15000.0,15.66,0.31,3.0,645,0,...,0,0,0,1,0,0,0,1,0,0
44996,37.0,0,65800.0,17,9000.0,14.07,0.14,11.0,621,0,...,0,0,0,1,0,0,1,0,0,0
44997,33.0,1,56942.0,7,2771.0,10.02,0.05,10.0,668,0,...,0,0,0,1,1,0,0,0,0,0
44998,29.0,1,33164.0,4,12000.0,13.23,0.36,6.0,604,0,...,0,0,0,1,0,1,0,0,0,0
44999,24.0,1,51609.0,1,6665.0,17.05,0.13,3.0,628,0,...,0,0,0,1,1,0,0,0,0,0

In [17]:
loan.loc[:, "person_income"] = np.log(loan["person_income"])
loan

,person_age,person_gender,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,...,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,22.0,0,11.183699,0,35000.0,16.02,0.49,3.0,561,0,...,0,0,0,1,0,0,0,0,1,0
1,21.0,0,9.415890,0,1000.0,11.14,0.08,2.0,504,1,...,0,0,1,0,0,1,0,0,0,0
2,25.0,0,9.428512,3,5500.0,12.87,0.44,3.0,635,0,...,1,0,0,0,0,0,0,1,0,0
3,23.0,0,11.286690,0,35000.0,15.23,0.44,2.0,675,0,...,0,0,0,1,0,0,0,1,0,0
4,24.0,1,11.099453,1,35000.0,14.27,0.53,4.0,586,0,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,10.778352,6,15000.0,15.66,0.31,3.0,645,0,...,0,0,0,1,0,0,0,1,0,0
44996,37.0,0,11.094375,17,9000.0,14.07,0.14,11.0,621,0,...,0,0,0,1,0,0,1,0,0,0
44997,33.0,1,10.949788,7,2771.0,10.02,0.05,10.0,668,0,...,0,0,0,1,1,0,0,0,0,0
44998,29.0,1,10.409220,4,12000.0,13.23,0.36,6.0,604,0,...,0,0,0,1,0,1,0,0,0,0
44999,24.0,1,10.851451,1,6665.0,17.05,0.13,3.0,628,0,...,0,0,0,1,1,0,0,0,0,0

In [18]:
loan.loc[:, "loan_amnt"] = np.log(loan["loan_amnt"])
loan

,person_age,person_gender,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,...,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,22.0,0,11.183699,0,10.463103,16.02,0.49,3.0,561,0,...,0,0,0,1,0,0,0,0,1,0
1,21.0,0,9.415890,0,6.907755,11.14,0.08,2.0,504,1,...,0,0,1,0,0,1,0,0,0,0
2,25.0,0,9.428512,3,8.612503,12.87,0.44,3.0,635,0,...,1,0,0,0,0,0,0,1,0,0
3,23.0,0,11.286690,0,10.463103,15.23,0.44,2.0,675,0,...,0,0,0,1,0,0,0,1,0,0
4,24.0,1,11.099453,1,10.463103,14.27,0.53,4.0,586,0,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,10.778352,6,9.615805,15.66,0.31,3.0,645,0,...,0,0,0,1,0,0,0,1,0,0
44996,37.0,0,11.094375,17,9.104980,14.07,0.14,11.0,621,0,...,0,0,0,1,0,0,1,0,0,0
44997,33.0,1,10.949788,7,7.926964,10.02,0.05,10.0,668,0,...,0,0,0,1,1,0,0,0,0,0
44998,29.0,1,10.409220,4,9.392662,13.23,0.36,6.0,604,0,...,0,0,0,1,0,1,0,0,0,0
44999,24.0,1,10.851451,1,8.804625,17.05,0.13,3.0,628,0,...,0,0,0,1,1,0,0,0,0,0

In [19]:
loan.columns

Index(['person_age', 'person_gender', 'person_income', 'person_emp_exp',
       'loan_amnt', 'loan_int_rate', 'loan_percent_income',
       'cb_person_cred_hist_length', 'credit_score',
       'previous_loan_defaults_on_file', 'loan_status',
       'person_education_Associate', 'person_education_Bachelor',
       'person_education_Doctorate', 'person_education_High School',
       'person_education_Master', 'person_home_ownership_MORTGAGE',
       'person_home_ownership_OTHER', 'person_home_ownership_OWN',
       'person_home_ownership_RENT', 'loan_intent_DEBTCONSOLIDATION',
       'loan_intent_EDUCATION', 'loan_intent_HOMEIMPROVEMENT',
       'loan_intent_MEDICAL', 'loan_intent_PERSONAL', 'loan_intent_VENTURE'],
      dtype='object')

In [20]:
X = loan[['person_age', 'person_gender', 'person_income', 'person_emp_exp',
       'loan_amnt', 'loan_int_rate', 'loan_percent_income',
       'cb_person_cred_hist_length', 'credit_score',
       'previous_loan_defaults_on_file',
       'person_education_Associate', 'person_education_Bachelor',
       'person_education_Doctorate', 'person_education_High School',
       'person_education_Master', 'person_home_ownership_MORTGAGE',
       'person_home_ownership_OTHER', 'person_home_ownership_OWN',
       'person_home_ownership_RENT', 'loan_intent_DEBTCONSOLIDATION',
       'loan_intent_EDUCATION', 'loan_intent_HOMEIMPROVEMENT',
       'loan_intent_MEDICAL', 'loan_intent_PERSONAL', 'loan_intent_VENTURE']]

X

,person_age,person_gender,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,...,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,22.0,0,11.183699,0,10.463103,16.02,0.49,3.0,561,0,...,0,0,0,1,0,0,0,0,1,0
1,21.0,0,9.415890,0,6.907755,11.14,0.08,2.0,504,1,...,0,0,1,0,0,1,0,0,0,0
2,25.0,0,9.428512,3,8.612503,12.87,0.44,3.0,635,0,...,1,0,0,0,0,0,0,1,0,0
3,23.0,0,11.286690,0,10.463103,15.23,0.44,2.0,675,0,...,0,0,0,1,0,0,0,1,0,0
4,24.0,1,11.099453,1,10.463103,14.27,0.53,4.0,586,0,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,10.778352,6,9.615805,15.66,0.31,3.0,645,0,...,0,0,0,1,0,0,0,1,0,0
44996,37.0,0,11.094375,17,9.104980,14.07,0.14,11.0,621,0,...,0,0,0,1,0,0,1,0,0,0
44997,33.0,1,10.949788,7,7.926964,10.02,0.05,10.0,668,0,...,0,0,0,1,1,0,0,0,0,0
44998,29.0,1,10.409220,4,9.392662,13.23,0.36,6.0,604,0,...,0,0,0,1,0,1,0,0,0,0
44999,24.0,1,10.851451,1,8.804625,17.05,0.13,3.0,628,0,...,0,0,0,1,1,0,0,0,0,0

In [21]:
y = loan['loan_status']

In [22]:
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.3)

In [23]:
logisticRegression = LogisticRegression(max_iter=5000)
logisticRegression

LogisticRegression(max_iter=5000)

In [24]:
logisticRegression.fit(X_train, y_train)
logisticRegression

LogisticRegression(max_iter=5000)

In [25]:
logisticRegression.coef_

array([[ 2.92522426e-02,  3.50551438e-02, -4.48326138e-01,
        -2.00151847e-02, -6.40055924e-01,  3.33090675e-01,
         1.29645316e+01, -1.19951668e-02, -8.36681614e-03,
        -7.56044700e+00,  6.74821100e-01,  6.73436543e-01,
         7.04478145e-01,  6.86773987e-01,  6.89212415e-01,
         9.97426044e-01,  1.24953968e+00, -4.52327547e-01,
         1.63408402e+00,  1.09924352e+00,  2.02802185e-01,
         1.12132038e+00,  8.01118240e-01,  3.80285977e-01,
        -1.76048116e-01]])

In [26]:
logisticRegression.intercept_

array([6.67279179])

In [28]:
y_predict = logisticRegression.predict(X_test)
print(y_predict)
# print(y)

[0 1 0 ... 0 0 0]

In [32]:
cm = confusion_matrix(y_test, y_predict)
cm

array([[9848,  668],
       [ 703, 2281]])